# https://www.dartlang.org/guides/language/analysis-options

analyzer:
  strong-mode: true

linter:
  rules:
    # http://dart-lang.github.io/linter/lints/

    # == error rules ==
    - avoid_empty_else
    - slash_for_doc_comments
    - always_declare_return_types
    - sort_constructors_first
    - comment_references
    - empty_statements
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unrelated_type_equality_checks
    - valid_regexps

    # == style rules ==
    - always_declare_return_types
    - always_specify_types
    - avoid_init_to_null
    - camel_case_types
    - empty_constructor_bodies
    - library_names
    - prefer_is_not_empty
    - super_goes_last
    - unnecessary_brace_in_string_interp
    - unnecessary_getters_setters
