name: dart_sample_game
version: 0.0.1
description: A sample command-line game application.
author:
  - Honza Bittner <the@honzabittner.cz>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
